# Numpy Notes

Reference: https://mp.weixin.qq.com/s/77aq0JQs8SX6molSxewOdQ

NumPy的关键用途是实现适用于矩阵和向量的数学运算。

In [1]:
import numpy as np 

## Numpy中的数组操作

In [4]:
# 创建数组
np.ones(3)
np.zeros(3)
np.random.random(3)

array([0.73153272, 0.82767112, 0.02032306])

In [6]:
# 数组的算术运算
data = np.array([1,2])
ones = np.ones(2)
data + ones
data * 1.6 # broadcasting

array([1.6, 3.2])

In [9]:
# 数组的切片操作
data[0] # return a value
data[0:] # return a array

2

In [11]:
# 聚合函数
data.max()
data.min()
data.sum()
data.mean()
data.prod() # product of all elements

2

## NumPy中的矩阵操作

In [16]:
# 创建矩阵
np.array([[1,2],[3,4]]) # input: list[[row1],[row2]]
np.ones((2,2))  # input: tuple(rows, columns)
np.zeros((3,2)) 
np.random.random((3,2))

array([[0.58657812, 0.17240919],
       [0.39692835, 0.11575789],
       [0.41764588, 0.7017165 ]])

In [22]:
# 矩阵的算术运算
data = np.array([[1,2],[3,4]])
ones = np.ones((2,2))
data + ones
ones_row = np.ones(2)
data + ones_row  # broadcasting

array([[2., 3.],
       [4., 5.]])

In [29]:
# 矩阵的切片
data = np.array([[1,2],[3,4],[5,6]]) 
data[0,1] # [row_index, column_index]
data[0:1,] # [row_begin:row_end, col_begin:col_end]
data[1:3,]
data[0:2,0]

6

In [31]:
# 矩阵的聚合
data.max() # group all
data.min()
data.max(axis =0) # group by column
data.max(axis =1) # group by row

array([5, 6])

In [32]:
# 矩阵的转置
data = np.array([[1,2],[3,4],[5,6]]) 
data.T # 转置

array([[1, 3, 5],
       [2, 4, 6]])

In [38]:
# 矩阵的重构
data = np.array([1,2,3,4,5,6])
data
data.reshape(2,3) # input: reshap(row_count, column_count)
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
# 多维矩阵
np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
np.ones((4,3,2))

24.0